services:

  nginx:
    image: nginx:stable
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - '.:/srv'
    ports:
      - '8080:80'
    depends_on:
      - php

  php:
    build: ./docker
    volumes:
      - '.:/srv'
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file:
      - .env

  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pa$$}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db_data:/var/lib/postgresql/data:rw


volumes:
  db_data:

